








100%|███████████████████████████████████████████████████████████████████████████████████| 100/100 [00:19<00:00,  5.22it/s]
Traceback (most recent call last):
  File "mult.py", line 153, in <module>
    train_autoencoder()
  File "mult.py", line 133, in train_autoencoder
    restored_fill_data[i, j] = X_test_tensor[i, j]
IndexError: index 13 is out of bounds for axis 1 with size 11